
.'Z:\RiskII\Tritch\Operation Loki\Non_Mon_Trans.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Straight_Rollers.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Waterfall.ps1'

.'Z:\RiskII\Tritch\Operation Loki\NA_Choice.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Cred_Qual.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Acct_Bal_FICO.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Prepaid_MIS.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Corp_Guarantor.ps1'
#.'Z:\RiskII\Tritch\Operation Loki\NA_Waterfall_CCL.ps1'
#.'Z:\RiskII\Tritch\Operation Loki\NA_Choice_CCL.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Daily_Auth_Tracking.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Portfolio_Vintage.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Vintage.ps1'
.'Z:\RiskII\Tritch\Operation Loki\FDS_Cash_Payments.ps1'
.'Z:\RiskII\Tritch\Operation Loki\FDS_CB_Refunds.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Over_Limit.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Credit_Line_Change.ps1'
.'Z:\RiskII\Tritch\Operation Loki\FICO_Score_Migration.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Auth_Waterfall.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Portfolio_Accounts.ps1'
#Overlimit_Trans.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Loss_Forecast.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Line_Exposure.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Return_Checks.ps1'
.'Z:\RiskII\Tritch\Operation Loki\FDS_Return_Checks.ps1'
#FDS_OFAC.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Delq_Report.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Data_Validation.ps1'
.'Z:\RiskII\Tritch\Operation Loki\POA_Certegy.ps1'
.'Z:\RiskII\Tritch\Operation Loki\POS_CLI.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Vintage_6.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_IDA_Vintage_3.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_IDA_Vintage_6.ps1'
#NA_Referrals.ps1'
#NA_MTM_Comp.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Ninty_Plus_Curve.ps1'
#IDA_Curve.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_13_Month_Waterfall.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Purchase_Activity.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Fraud.ps1'
.'Z:\RiskII\Tritch\Operation Loki\NA_Referrals.ps1'
.'Z:\RiskII\Tritch\Operation Loki\GCL_Waterfall.ps1'
.'Z:\RiskII\Tritch\Operation Loki\Corp_Acct_Net_Purch.ps1'